### ISSUE TITLE
Maybe we should allow no inputs

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/evaluations-service#46]
https://github.com/coding-eval-platform/evaluations-service/blob/843919f87ad7cf97c73bba524ba8f08033ad0b62/evaluations-service-core/evaluations-service-models/src/main/java/ar/edu/itba/cep/evaluations_service/models/TestCase.java#L220

@lobo Que te parece?

Similar to coding-eval-platform/executor-service#24

**Comment by lobo** [comment]
I think we should allow no inputs at all.

For example, they give you a code snippet with an unsorted array in the given code snippet, and they put an estimated output (ie, the sorted array). So there's no input here and I think it's something valid as an exercise :)

**Comment by juanmbellini** [comment]
Ok. So I reopen the issue to allow this

**Comment by juanmbellini** [comment]
Yes, admit. Will be fixed in #80
