### ISSUE TITLE
What do we do in case of an InitializationError or an UnknownError?

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/evaluations-service#75]
in #74 support for the new results of the [Executor Service](https://github.com/coding-eval-platform/executor-service) is added. However, if the returned result is an `InitializationErrorExecutionResult` or an `UnknownErrorExecutionResult`, nothing is done.

What should we do? Retry? how many retries?

**Comment by lobo** [comment]
@juanmbellini I think that service should retry every 3 times, after 3s of receiving the error. Once the it happens for the 3rd time, nothing is done (by now). In the future, we can either mark the exercise on the DB for later evaluation of the teacher. In the UI, we'll put the 3 retries and then a final message to either "call the teacher" (if in an exam) or "refresh page" (if in playground).

**Comment by juanmbellini** [comment]
Okey, this will be done later

**Comment by juanmbellini** [comment]
will be solved in #76
