### ISSUE TITLE
Should we allow empty expected outputs list?

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/evaluations-service#84]
Similar to #38, but for expected outputs

**Comment by juanmbellini** [comment]
@lobo What do you think about this? Does it makes sense?

**Comment by lobo** [comment]
yes

**Comment by juanmbellini** [comment]
Okey, so we allow it or not? Up to now we don't allow it.

**Comment by lobo** [comment]
Oh, my mistake. Test Cases should not allow "expected outputs" to be empty.
