### ISSUE TITLE
If the user is not admin, but teacher, only list its own exams? And when accessing an exam by its id?

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/evaluations-service#88]
Up to now, all exams are listed if the user is admin or teacher. Should we change this behaviour? Should we list only the said user's exams? What about accessing an exam by its id?

Continues #18

**Comment by lobo** [comment]
> Should we list only the said user's exams? 

Only his exams.

> What about accessing an exam by its id?

Yes
