### ISSUE TITLE
Should we allow an admin to submit/delete an exercise solution?

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/evaluations-service#92]
It might be a useful feature. However, if present, this feature can introduce fraud.

Continues #18

**Comment by lobo** [comment]
only submissions I'd say - so anyone can see the entire picture of the exam and its solutions

**Comment by juanmbellini** [comment]
I mean... should we allow an ADMIN user to submit or delete a solution? If it is allowed, any admin could send a solution in the name of a student, which is a fraud. @lobo

**Comment by lobo** [comment]
I think we should not, only THE teacher owner of that.
